pipeline:
  gcr:
    image: plugins/gcr
    repo: betacle-202016/master/frontend
    tags: latest
    secrets:
      - gcr_json_key
      - frontend_host
      - frontend_port
      - frontend_url
      - backend_url
    build_args_from_env:
      - frontend_host
      - frontend_port
      - frontend_url
      - backend_url
  deploy:
    image: quay.io/honestbee/drone-kubernetes
    kubernetes_server: ${KUBERNETES_SERVER}
    kubernetes_token: ${KUBERNETES_TOKEN}
    kubernetes_cert: ${KUBERNETES_CERT}
    deployment: frontend-deployment
    repo: betacle-202016/master/frontend
    container: frontend-container
    namespace: default
    tag: latest
    secrets: [kubernetes_server, kubernetes_token, kubernetes_cert]
    when:
      branch: [master]
