pipeline:
  gcr:
    image: plugins/gcr
    repo: betacle-202016/master/frontend
    tags: latest
    secrets:
      - gcr_json_key
      - frontend_host
      - FRONTEND_HOST
      - frontend_port
    build_args_from_env:
      - frontend_host
      - FRONTEND_HOST