pipeline:
  printenv:
    image: busybox
    secrets: [gcr_json_key, frontend_host, frontend_port]
    commands:
      - export FRONTEND_HOST=$FRONTEND_HOST
  gcr:
    image: plugins/gcr
    repo: betacle-202016/master/frontend
    privileged: true
    environment:
      - HI=1
    commands:
      - export FRONTEND_HOST=0.0.0.0
    tags: latest
    secrets: [gcr_json_key, frontend_host, frontend_port]