pipeline:
  printenv:
    image: busybox
    secrets: [gcr_json_key, frontend_host, frontend_port]
    commands:
      - export $FRONTEND_HOST
  gcr:
    image: plugins/gcr
    repo: betacle-202016/master/frontend
    tags: latest
    secrets: [gcr_json_key, frontend_host, frontend_port]