pipeline:
  gcr:
    image: plugins/gcr
    repo: betacle-202016/master/frontend
    environment:
      - 'FRONTEND_PORT=${FRONTEND_PORT}'
    tags: latest
    secrets: [gcr_json_key, frontend_host, frontend_port]