pipeline:
  gcr:
    image: plugins/gcr
    repo: betacle-202016/master/frontend
    tags: latest
    secrets:
      - gcr_json_key
      - frontend_host
      - frontend_port
      - frontend_url
      - backend_url
    build_args_from_env:
      - frontend_host
      - frontend_port
      - frontend_url
      - backend_url