FROM node:9-alpine

COPY . /app
WORKDIR /app

ARG FRONTEND_HOST
ARG FRONTEND_PORT
ARG FRONTEND_URL
ARG BACKEND_URL
ARG GA_ID

# Setting up env variables for frontend
ENV HOST=$FRONTEND_HOST
ENV PORT=$FRONTEND_PORT
ENV FRONTEND_URL=$FRONTEND_URL
ENV BACKEND_URL=$BACKEND_URL
ENV GA_ID=$GA_ID

# Installing yarn
RUN npm install
RUN npm run build

CMD npm run start

EXPOSE 5000